name: Python module

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py develop

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=18 --max-line-length=127 --statistics

    - name: Bandit Check
      uses: jpetrucciani/bandit-check@1.6.2
      with:
        path: './riffdog'

    - name: Test with tox
      run: |
        pip install tox
        tox

